---
title: "Learning Analytics"
author: "ML"
date: '2022-07-12'
output: word_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

load packages

```{r}

library(tidyverse)
library(janitor)

```


## Open University Learning Analytics Dataset

Download Open University Learning Analytics Dataset (OULAD) from https://analyse.kmi.open.ac.uk/open_dataset#description

```{r}

assessments <- readr::read_delim(file = "C:/EdReports/NORC_Infinite Campus_USC/OULAD/assessments.csv", delim = ",")

courses <- readr::read_delim(file = "C:/EdReports/NORC_Infinite Campus_USC/OULAD/courses.csv", delim = ",")

studentAssessment <- readr::read_delim(file = "C:/EdReports/NORC_Infinite Campus_USC/OULAD/studentAssessment.csv", delim = ",")

studentInfo <- readr::read_delim(file = "C:/EdReports/NORC_Infinite Campus_USC/OULAD/studentInfo.csv", delim = ",")

studentRegistration <- readr::read_delim(file = "C:/EdReports/NORC_Infinite Campus_USC/OULAD/studentRegistration.csv", delim = ",")

studentVle <- readr::read_delim(file = "C:/EdReports/NORC_Infinite Campus_USC/OULAD/studentVle.csv", delim = ",")

vle <- readr::read_delim(file = "C:/EdReports/NORC_Infinite Campus_USC/OULAD/vle.csv", delim = ",")

```

glimpse

```{r}

glimpse(assessments)
glimpse(courses)
glimpse(studentAssessment)
glimpse(studentInfo)
glimpse(studentRegistration)
glimpse(studentVle)
glimpse(vle)

```

